//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_tab
    {
        public int App_id { get; set; }
        public int Job_id { get; set; }
        public int User_id { get; set; }
        public System.DateTime Application_date { get; set; }
        public string Resume { get; set; }
        public string Status { get; set; }
    }
}
