//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacc_table
    {
        public int Job_id { get; set; }
        public int Comp_id { get; set; }
        public string Job_title { get; set; }
        public string Job_description { get; set; }
        public string Skills { get; set; }
        public int Experience { get; set; }
        public string Location { get; set; }
        public string Salary_range { get; set; }
        public string Job_type { get; set; }
        public System.DateTime Posted_date { get; set; }
        public System.DateTime Last_date { get; set; }
        public string Status { get; set; }
    }
}
